### ISSUE TITLE
awesome-tools

### ISSUE THREAD

**Issue by n3taway** [n3taway/awesome-tools#1]
# mbp pro 13'  osx    
### 终端
- Iterm 2 
- ~~nGo2Shell~~ -> OpenInTerminal 用途:当前目录打开终端
######  终端插件
- zsh oh-my-zsh

### 命令行
- brew 必备 https://zhuanlan.zhihu.com/p/111014448 
`/bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"`
brew 安装 fish
brew install fish
设置 fish 为主要的 shell 需要注意 bin 的目录
brew 已安装应用的路径`/opt/homebrew/bin`

- tree 树视图展示目录结构
- ~~nodejs版本管理 nvm npm版本切换 Usage: nvm alias default v10.x.x~~
- nodejs版本管理 fnm 锈化🦀 版本切换 Usage: fnm default 10.x.x
   _fnm设置了默认版本不生效，请设置 [Shell Setup](https://github.com/Schniz/fnm#shell-setup)_
```
如何选择
如果你不确定该用哪个，可以遵循以下原则：

环境变量（如 PATH、EDITOR 等）通常放在 .zprofile 中。

交互式配置（如别名、插件、提示符等）通常放在 .zshrc 中。
```
- sdkman java版本管理 Usage: sdk list
  - sdk current 查看当前软件版本
  - sdk install java sdk install maven
### 资源管理器
- QSpace

### 翻译
- Bob 支持ocr翻译

### VScode 插件
- Auto Close Tag
- Auto Rename Tag
- Bookmarks
- Bracket Pair Colorizer
- Code Runner
- Code Spell Checker 
- CSS Peek
- Dracula official
- EditorConfig for VS Code
- ES7 React/Redux/GraphQL/React-Native snippets
- ESLint
- Git History
- GitLens — Git supercharged
- javascript console utils
- Live Server
- markdownlint
- Path Autocomplete
- Quokka.js
- stylelint
- Sublime Text Keymap and Settings Importer
- TabNine
- Todo Tree
- TSLint (deprecated)
- TypeScript Importer
- Vetur
- vscode-icons

### 启动工具
- Alfred
######  工作流
- [youdao](https://github.com/whyliam/whyliam.workflows.youdao)
- [CodeVar](https://github.com/xudaolong/CodeVar)
### 笔记
- Typora  markdown 
- Joplin 
- Xmind 思维导图
- mindMaster 思维导图 多端同步
- 滴答清单 todo
- 语雀
- flomo浮墨笔记 瞬时灵感/想法通过微信同步到浮墨
- -

### 系统/效率工具
- 柠檬 垃圾清理
- Bartender 顶部图标过多 隐藏
- Snipaste 截图 
- Scroll Reverser 鼠标滚动控制
- KeepingYouAwake 合盖禁止休眠
- Magnet 应用窗口布局
- eZIP 解压缩工具 / maczip
- SwitchHosts 更新host
- Easy New File 新建文件
- HandShaker 安卓手机资源管理
- kap 录屏
- LICEcap 录屏
- vm Fusion 虚拟机
- Transmit 远端文件管理
- [cacher 代码片段管理](https://www.cacher.io/) 
- SlowQuitApps 防止不小心 command + q

### 音影娱乐
- Boom 3D 音乐声场控制
- lx-music-desktop 洛雪音乐🤙
- pap.er 浏览/切换 壁纸

**Comment by n3taway** [comment]
# for window
### 资源管理器
- QTTabBar
- nodejs版本管理[nvm-windows]( https://github.com/coreybutler/nvm-windows)  `$ nvm use 16.20.0`
> [如果在安装nvm之前独立安装过nodejs，请删除C:\Program Files\nodejs](https://stackoverflow.com/questions/47017812/nvm-use-does-not-switch-node-versions)


- 解决git clone代码，文件名过长错误
`git config --system core.longpaths true`
或编辑`gitconfig`文件
`"C:\Program Files\Git\etc\gitconfig"`
```bash
...
[core]
	autocrlf = true
	fscache = true
+	longpaths = true
	symlinks = false
[pull]
	rebase = false
...
```
- [vscode中拆分终端创建失败](https://zhuanlan.zhihu.com/p/343799308)
- [nrm安装后报错](https://juejin.cn/post/7212960463730819127)
- AutoHotKey
```
#NoTrayIcon
!a::
send,^{a}
return
!c::
send,^{c}
return
!v::
send,^{v}
return
!x::
send,^{x}
return
!s::
send,^{s}
return
!f::
send,^{f}
return
!z::
send,^{z}
return
!w::
send,^{w}
return
!d::
send,^{d}
return
!r::
send,^{r}
return
!t::
send,^{t}
return

; 双击ALT键打开cmd并执行指令
~Alt::
if (A_PriorHotkey <> "~Alt" or A_TimeSincePriorHotkey > 400)
{
    KeyWait, Alt
    return
}
Send ^c
ClipWait
Run, cmd /c fy %Clipboard% & pause
Return

F8::
msgbox,4100,'AutoHotKey exit success','AutoHotKey exit success'!,1
exitapp
return
```
- windows 11 cmd 乱码，search: win11下永久设置cmd编码为utf-8

**Comment by n3taway** [comment]
### projj config.json
```json
{
    "base": [
        "D:\\codes"
    ],
    "hooks": {
        "postadd": "git_config_user"
    },
    "postadd": {
        "192.168.122.230": {
            "name": "a",
            "email": "b@c.d"
        }
    },
    "alias": {
        "github://": "https://github.com/"
    }
}
```
## projj 报错
> 忽略报错信息，在用户目录创建.projj目录，在目录下创建config.json配置。
```bash
C:\Users\xxx>projj init
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:429:7)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\nvm\v16.20.0\node_modules\projj\lib\base_command.js:17:24)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by n3taway** [comment]
> 
projj的作者似乎没有维护，自己fork了单独的版本在使用 projjj 、projjj-hooks

**Comment by n3taway** [comment]
> ### projj config.json
> ```json
> {
>     "base": [
>         "D:\\codes"
>     ],
>     "hooks": {
>         "postadd": "git_config_user"
>     },
>     "postadd": {
>         "192.168.122.230": {
>             "name": "a",
>             "email": "b@c.d"
>         }
>     },
>     "alias": {
>         "github://": "https://github.com/"
>     }
> }
> ```
> 
> ## projj 报错
> > 忽略报错信息，在用户目录创建.projj目录，在目录下创建config.json配置。
> 
> ```shell
> C:\Users\xxx>projj init
> node:internal/validators:162
>     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
>     ^
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
>     at new NodeError (node:internal/errors:387:5)
>     at validateString (node:internal/validators:162:11)
>     at Object.join (node:path:429:7)
>     at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\nvm\v16.20.0\node_modules\projj\lib\base_command.js:17:24)
>     at Module._compile (node:internal/modules/cjs/loader:1196:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
>     at Module.load (node:internal/modules/cjs/loader:1074:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
>     at Module.require (node:internal/modules/cjs/loader:1098:19)
>     at require (node:internal/modules/cjs/helpers:108:18) {
>   code: 'ERR_INVALID_ARG_TYPE'
> }
> ```


**projj的作者似乎没有维护了，自己fork了单独的版本在用 projjj 、projjj-hooks**

**Comment by n3taway** [comment]
# for Android
- clash   不允许某个app走代理：设置-> 网络-> （访问控制模式）+（访问控制应用包列表）

**Comment by n3taway** [comment]
任务切换面板显示到所有显示器上
https://gist.github.com/jthodge/c4ba15a78fb29671dfa072fe279355f0
